/**
 * `@rbxts/lucide-react` — the Lucide icon set as React components.
 *
 * ```tsx
 * import Search from "@rbxts/lucide-react/icons/search";
 *
 * <Search size={24} color={Color3.fromRGB(255, 255, 255)} />
 * ```
 *
 * Each icon is an ordinary compiled `SvgAsset` behind `@rbxts/svg-react`'s
 * `<Svg>`. There is no XML at runtime, no uploaded image asset and no
 * approximation out of `Frame`s — the same compiler, IR, rasterizer and shared
 * raster cache that a project's own `.svg` imports use, with the compilation
 * done here instead of in the consumer's build.
 *
 * A renderer must be installed once at startup, exactly as for `<Svg>`:
 *
 * ```ts
 * import { installEditableImageRenderer } from "@rbxts/svg";
 *
 * installEditableImageRenderer();
 * ```
 *
 * # Which import to use
 *
 * ```tsx
 * import Search from "@rbxts/lucide-react/icons/search";   // one module
 * import { Search } from "@rbxts/lucide-react";            // all of them
 * ```
 *
 * Both work. They do not cost the same. roblox-ts has no tree shaking, so the
 * barrel below compiles to a module that requires every icon module in the
 * package — around two thousand of them — whatever a consumer names in the
 * braces. The per-icon subpath requires exactly one. Reach for the barrel when
 * icon names are being chosen dynamically or when the count is large enough
 * that it stops mattering; reach for the subpath otherwise. `docs/LUCIDE.md`
 * has the measurements.
 */

export { createLucideIcon } from "./createLucideIcon";
export type { LucideIcon, LucideIconProps } from "./createLucideIcon";

// Generated by `pnpm generate:lucide`. Every icon, under its Lucide name.
export * from "./generated";
