/**
 * `@rbxts/lucide-vide` — the Lucide icon set as Vide components.
 *
 * ```tsx
 * import Search from "@rbxts/lucide-vide/icons/search";
 *
 * const size = source(24);
 * const colour = source(Color3.fromRGB(255, 255, 255));
 *
 * <Search size={size} color={colour} />
 * ```
 *
 * Every prop is reactive, because every prop is `<Svg>`'s: this package adds no
 * effects and no state of its own. Recolouring a Lucide icon costs one
 * `ImageColor3` write and no rasterization, which is a property of
 * `@rbxts/svg-vide` and the shared render cache rather than of anything here.
 *
 * A renderer must be installed once at startup:
 *
 * ```ts
 * import { installEditableImageRenderer } from "@rbxts/svg";
 *
 * installEditableImageRenderer();
 * ```
 *
 * # Which import to use
 *
 * ```tsx
 * import Search from "@rbxts/lucide-vide/icons/search";   // one module
 * import { Search } from "@rbxts/lucide-vide";            // all of them
 * ```
 *
 * Both work. They do not cost the same. roblox-ts has no tree shaking, so the
 * barrel below compiles to a module that requires every icon module in the
 * package — around two thousand of them — whatever a consumer names in the
 * braces. The per-icon subpath requires exactly one. `docs/LUCIDE.md` has the
 * measurements.
 *
 * A React and a Vide application in one game share their rasters: the two
 * packages embed their own copies of each icon's compiled bytes, but the bytes
 * are identical, so the asset hashes are identical and `@rbxts/svg`'s cache
 * sees one icon rather than two.
 */

export { createLucideIcon } from "./createLucideIcon";
export type { LucideIcon, LucideIconProps } from "./createLucideIcon";

// Generated by `pnpm generate:lucide`. Every icon, under its Lucide name.
export * from "./generated";
