/**
 * The single point where the native binary is loaded.
 *
 * Everything else in this package imports from here, so consumers never depend
 * on a platform-specific `.node` file directly and there is exactly one place
 * to change if the loading strategy does.
 *
 * `@rbxts/svg-native`'s own `index.js` (generated by `napi build --platform`)
 * resolves the right prebuilt binary for the host: a local `.node` file during
 * development, or the matching `@rbxts/svg-native-<platform>-<arch>` optional
 * dependency once published. Users never need `cargo` or `rustc`.
 */

/** The subset of the native binding this package uses. */
interface NativeBinding {
	compileSvg(
		source: string | Buffer,
		options?: {
			dpi?: number;
			allowUnsupported?: boolean;
			sourceName?: string;
		},
	): NativeCompiledSvg;
	decodeSvgIr(data: Buffer): NativeDecodedSvg;
	renderSvgIr(
		data: Buffer,
		width: number,
		height: number,
		options?: NativeRasterOptions,
	): NativeRasterImage;
	irVersion(): number;
}

/** Options for the reference rasterizer. */
export interface NativeRasterOptions {
	alphaMask?: boolean;
	/** `[r, g, b]`, each 0-255. */
	currentColor?: number[];
	strokeWidth?: number;
	absoluteStrokeWidth?: boolean;
}

/** A reference-rendered image: straight RGBA8, row-major from the top-left. */
export interface NativeRasterImage {
	width: number;
	height: number;
	pixels: Buffer;
}

interface NativeCompiledSvg {
	data: Buffer;
	width: number;
	height: number;
	viewBoxX: number;
	viewBoxY: number;
	preserveAspectRatio: string;
	flags: number;
	hash: string;
	irVersion: number;
	shapeCount: number;
	diagnostics: NativeDiagnostic[];
}

interface NativeDiagnostic {
	severity: string;
	code: string;
	message: string;
	tag?: string;
	id?: string;
	path?: string;
	line?: number;
	column?: number;
	rendered: string;
}

/** Shape of `decodeSvgIr`'s result. Used for tooling and tests. */
export interface NativeDecodedSvg {
	irVersion: number;
	viewBoxX: number;
	viewBoxY: number;
	width: number;
	height: number;
	preserveAspectRatio: string;
	flags: number;
	shapes: NativeDecodedShape[];
}

export interface NativeDecodedShape {
	fill?: NativeDecodedPaint;
	fillRule?: string;
	stroke?: NativeDecodedPaint;
	strokeWidth?: number;
	lineCap?: string;
	lineJoin?: string;
	miterLimit?: number;
	paintOrder: string;
	commands: NativeDecodedCommand[];
}

export interface NativeDecodedPaint {
	kind: string;
	r: number;
	g: number;
	b: number;
	alpha: number;
}

export interface NativeDecodedCommand {
	op: string;
	points: number[];
}

let cached: NativeBinding | undefined;

/**
 * Loads the native binding, with an error that explains what to do.
 *
 * A missing prebuilt binary is the one failure a user is likely to hit on an
 * unusual platform, and "cannot find module" would tell them nothing useful.
 */
export function loadNative(): NativeBinding {
	if (cached !== undefined) {
		return cached;
	}
	try {
		// eslint-disable-next-line @typescript-eslint/no-require-imports
		cached = require("@rbxts/svg-native") as NativeBinding;
		return cached;
	} catch (cause) {
		const detail = cause instanceof Error ? cause.message : String(cause);
		throw new Error(
			`@rbxts/svg-compiler could not load its native binary for ${process.platform}-${process.arch}.\n\n` +
				`This normally means no prebuilt binary is published for this platform yet.\n` +
				`Building from source requires a Rust toolchain (https://rustup.rs) and:\n` +
				`  pnpm --filter @rbxts/svg-native run build\n\n` +
				`Underlying error: ${detail}`,
			{ cause },
		);
	}
}

export type { NativeBinding, NativeCompiledSvg, NativeDiagnostic };
