/**
 * The source-path → generated-module-path mapping, and nothing else.
 *
 * # Why this is its own module
 *
 * Two independent tools need this mapping and must never disagree about it:
 *
 * ```text
 * rbxts-svg build   →  writes  src/svg-cache/icons/search.svg.ts
 * @rbxts/svg-transformer → rewrites "./icons/search.svg"
 *                               to  "./svg-cache/icons/search.svg"
 * ```
 *
 * If the generator and the transformer computed that path separately they would
 * eventually drift, and the failure mode would be a broken `require` at runtime
 * rather than a build error. So there is exactly one definition, here.
 *
 * This module is deliberately free of any dependency on the native compiler:
 * importing it must not load `@rbxts/svg-native`. The transformer runs inside
 * `rbxtsc` and has no business pulling a Rust binary into that process — it
 * only maps paths. `@rbxts/svg-compiler/paths` is the entry point for that.
 *
 * Everything here is a pure function of its arguments: no filesystem reads, no
 * cwd, no clock. Given the same paths and options, every machine computes the
 * same specifier.
 */

import { posix, win32, resolve as nativeResolve, relative as nativeRelative, join as nativeJoin, sep as nativeSep } from "node:path";

/** Marks a file as generated, and is what identifies files safe to prune. */
export const GENERATED_HEADER = "// Generated by @rbxts/svg — do not edit.";

/** File suffix appended to the source name, e.g. `search.svg` → `search.svg.ts`. */
export const GENERATED_SUFFIX = ".ts";

/** The extension that makes a module specifier ours to rewrite. */
export const SVG_EXTENSION = ".svg";

/**
 * Name of the generated ambient declaration that types `import x from "*.svg"`.
 *
 * It lives beside the generated modules, inside the project's source tree, so
 * TypeScript picks it up through the `include` globs the project already has —
 * no `typeRoots` entry, no triple-slash reference, and nothing for a consumer
 * to hand-write. See `generateAmbientModuleSource` in `generate.ts`.
 */
export const AMBIENT_MODULE_FILE = "svg-modules.d.ts";

/**
 * Default directory for generated modules, relative to the source root.
 *
 * Deliberately *not* dot-prefixed. TypeScript's `include` globs skip
 * directories whose name begins with a dot, so a `.svg-cache/` default would
 * leave every generated module outside the program and every import failing
 * with "Cannot find module" — with no hint as to why. Keeping the generated
 * output out of source control is `.gitignore`'s job, not the directory name's.
 */
export const DEFAULT_OUT_DIR = "svg-cache";

/** The two paths that decide where a generated module lands. */
export interface SvgPathOptions {
	/** Source root; generated paths mirror the source tree relative to this. */
	readonly rootDir: string;
	/** Where generated modules are written. Defaults to `<rootDir>/svg-cache`. */
	readonly outDir?: string | undefined;
}

/**
 * The slice of `node:path` this module uses.
 *
 * Parameterized so the Windows mapping can be tested from a POSIX machine and
 * vice versa — `node:path` exports `win32` and `posix` objects that both
 * satisfy this. Production callers use the platform default and never pass it.
 */
export interface PathFlavor {
	readonly sep: string;
	resolve(...paths: string[]): string;
	relative(from: string, to: string): string;
	join(...paths: string[]): string;
}

const nativeFlavor: PathFlavor = {
	sep: nativeSep,
	resolve: nativeResolve,
	relative: nativeRelative,
	join: nativeJoin,
};

/** `node:path`'s Windows implementation, for cross-platform tests. */
export const windowsPaths: PathFlavor = win32;
/** `node:path`'s POSIX implementation, for cross-platform tests. */
export const posixPaths: PathFlavor = posix;

/** Absolute path of the directory generated modules are written to. */
export function resolveOutDir(
	options: SvgPathOptions,
	flavor: PathFlavor = nativeFlavor,
): string {
	const rootDir = flavor.resolve(options.rootDir);
	return options.outDir === undefined
		? flavor.join(rootDir, DEFAULT_OUT_DIR)
		: flavor.resolve(options.outDir);
}

/**
 * Whether `path` is inside `directory` (or is it).
 *
 * The `..` test is the whole point: it is what stops `../../../outside.svg`
 * from being mapped to a generated module the build would never produce.
 */
export function isInside(
	path: string,
	directory: string,
	flavor: PathFlavor = nativeFlavor,
): boolean {
	const rel = flavor.relative(flavor.resolve(directory), flavor.resolve(path));
	return rel === "" || (!rel.startsWith("..") && !isAbsoluteish(rel, flavor));
}

/**
 * A `relative()` result can come back absolute when the two paths share no
 * root — different Windows drives, say. That is "outside" just as surely as
 * a leading `..` is.
 */
function isAbsoluteish(rel: string, flavor: PathFlavor): boolean {
	return rel.startsWith(flavor.sep) || /^[A-Za-z]:/.test(rel);
}

/** Thrown when an SVG lies outside the source root the build scans. */
export class SvgOutsideRootError extends Error {
	override readonly name = "SvgOutsideRootError";

	constructor(
		readonly sourcePath: string,
		readonly rootDir: string,
	) {
		super(
			`${sourcePath} is outside rootDir ${rootDir}; every SVG must live inside the project root ` +
				`so its generated module has a stable location.`,
		);
	}
}

/**
 * Where the generated module for a source file lives.
 *
 * A pure function of the two paths, so a transformer can compute the rewritten
 * import specifier without consulting any build state.
 *
 * Throws [`SvgOutsideRootError`] for a source outside `rootDir`. The generator
 * never produces such a module, so the transformer must never point at one:
 * both sides share this single acceptance rule.
 */
export function generatedModulePath(
	sourcePath: string,
	options: SvgPathOptions,
	flavor: PathFlavor = nativeFlavor,
): string {
	const rootDir = flavor.resolve(options.rootDir);
	const outDir = resolveOutDir(options, flavor);
	const relativePath = flavor.relative(rootDir, flavor.resolve(sourcePath));

	if (relativePath.startsWith("..") || isAbsoluteish(relativePath, flavor)) {
		throw new SvgOutsideRootError(sourcePath, rootDir);
	}
	return flavor.join(outDir, relativePath + GENERATED_SUFFIX);
}

/** Absolute path of the generated `*.svg` ambient declaration. */
export function ambientModulePath(
	options: SvgPathOptions,
	flavor: PathFlavor = nativeFlavor,
): string {
	return flavor.join(resolveOutDir(options, flavor), AMBIENT_MODULE_FILE);
}

/**
 * The module specifier that `importerDir` should use to reach `sourcePath`'s
 * generated module.
 *
 * ```text
 * importer:  src/screens/settings/Settings.tsx
 * source:    src/assets/icons/search.svg
 * result:    "../../svg-cache/assets/icons/search.svg"
 * ```
 *
 * The `.ts` suffix is dropped: roblox-ts pins `moduleResolution: "Node10"`,
 * where `./x.svg` already resolves to `x.svg.ts` by extension substitution.
 * Leaving `.ts` on would be both redundant and, under TypeScript's rules for
 * explicit extensions, wrong.
 */
export function generatedModuleSpecifier(
	importerDir: string,
	sourcePath: string,
	options: SvgPathOptions,
	flavor: PathFlavor = nativeFlavor,
): string {
	const modulePath = generatedModulePath(sourcePath, options, flavor);
	const withoutSuffix = modulePath.slice(0, -GENERATED_SUFFIX.length);
	const rel = flavor.relative(flavor.resolve(importerDir), withoutSuffix);
	return toModuleSpecifier(rel);
}

/**
 * Turns a filesystem-relative path into a TypeScript module specifier.
 *
 * Module specifiers are POSIX regardless of host, and a specifier without a
 * leading `./` is a *package* name — `svg-cache/foo.svg` would be looked up in
 * `node_modules`. Both corrections are what make the output identical on
 * Windows and POSIX.
 */
export function toModuleSpecifier(relativePath: string): string {
	const slashed = relativePath.split("\\").join("/");
	if (slashed === "") {
		return ".";
	}
	return slashed.startsWith("./") || slashed.startsWith("../") || slashed === ".." || slashed === "."
		? slashed
		: `./${slashed}`;
}

/** Whether a module specifier names an SVG, and is therefore ours to rewrite. */
export function isSvgSpecifier(specifier: string): boolean {
	return specifier.toLowerCase().endsWith(SVG_EXTENSION);
}

/**
 * Whether a specifier is relative, and so resolvable against the importer.
 *
 * Non-relative `.svg` specifiers (`@/icons/x.svg`, `assets/x.svg`) would need
 * `baseUrl`/`paths` resolution that roblox-ts does not support; they get a
 * diagnostic rather than a guess.
 */
export function isRelativeSpecifier(specifier: string): boolean {
	return specifier.startsWith("./") || specifier.startsWith("../");
}
