/**
 * The text of every generated file.
 *
 * # Why there is one emitter and not two
 *
 * `@rbxts/lucide-react` and `@rbxts/lucide-vide` differ in exactly one place:
 * the hand-written `createLucideIcon.tsx` at each package's root, which is the
 * file that knows what a React element or a Vide node is. Everything *this*
 * module emits — the per-icon modules, the alias modules, the barrel — refers
 * to that file by the same relative path and contains no framework vocabulary
 * at all.
 *
 * So the generated trees are byte-identical between the two packages, and the
 * requirement that "the vector data must not differ between frameworks" is not
 * something a test has to discover afterwards: there is one function producing
 * one string, called twice. The test still exists, because a guarantee worth
 * having is worth checking, but it is checking a tautology rather than a
 * coincidence.
 *
 * # Why the modules are this small
 *
 * There are 2025 of them per package. A line here is 2025 lines in the source
 * tree, 2025 lines of emitted Luau, and 2025 lines in the diff of every
 * upstream bump. A generated icon module is therefore a header, an import, an
 * asset and a factory call — no cache keys, no colour handling, no lifecycle,
 * nothing that `@rbxts/svg` and the two bindings already own.
 */

import { ASSET_IMPORT_STATEMENT, generateAssetExpression } from "@rbxts/svg-compiler";

import type { CompiledLucideIcon } from "./compile.js";
import type { LucideManifest, LucideManifestEntry } from "./manifest.js";

/**
 * Marks a file as generated, and is what makes stale-file pruning safe.
 *
 * Pruning only ever deletes a file that starts with this, so a mistake in the
 * output path cannot destroy a hand-written source file.
 */
export const GENERATED_MARKER = "// Generated by tools/lucide";

/** One generated file: a package-relative path and its full contents. */
export interface GeneratedFile {
	/** Relative to the package root, e.g. `src/generated/icons/search.tsx`. */
	readonly path: string;
	readonly contents: string;
}

/**
 * A concise, timestamp-free provenance line.
 *
 * Concise because it is repeated 2025 times per package; timestamp-free because
 * generating twice must produce identical bytes. The detail that does not fit
 * on one line lives in `docs/LUCIDE.md`, once.
 */
function header(version: string, detail: string): string {
	return `${GENERATED_MARKER} from lucide-static ${version} (${detail}). Do not edit.`;
}

/**
 * A canonical icon: the compiled asset, wrapped once.
 *
 * The asset expression comes from `@rbxts/svg-compiler`, the same function the
 * `.svg`-import modules use. There is one definition of how serialized IR
 * becomes an `SvgAsset`, and this is a caller of it rather than a second copy.
 */
export function renderIconModule(
	icon: CompiledLucideIcon,
	exportName: string,
	version: string,
): string {
	return [
		header(version, icon.sourceLabel),
		ASSET_IMPORT_STATEMENT,
		"",
		'import { createLucideIcon } from "../../createLucideIcon";',
		"",
		`export const ${exportName} = createLucideIcon(`,
		`\t${generateAssetExpression(icon.compiled, "\t")},`,
		");",
		"",
		`export default ${exportName};`,
		"",
	].join("\n");
}

/**
 * An alias: a second name for an icon, and not a second copy of it.
 *
 * Upstream ships an alias as a duplicate `.svg`, but duplicating the compiled
 * IR here would add real bytes to both packages for no runtime benefit — the
 * two would compile to the same hash and share a cache entry anyway. A
 * re-export gives the alias its own resolvable module, its own subpath import,
 * and no artwork of its own.
 */
export function renderAliasModule(
	entry: LucideManifestEntry,
	canonicalExportName: string,
	version: string,
): string {
	const detail = `${entry.sourceFile} → ${entry.aliasOf}`;
	// A pure re-export, with no local binding of its own. An alias and its
	// target sometimes want the *same* identifier — `arrow-down-01` and
	// `arrow-down-0-1` both spell `ArrowDown01` — and `const X = X` after
	// importing `X` is a redeclaration rather than an alias. Re-exporting has
	// no such edge, and it emits one `require` of the canonical module.
	const renamed =
		canonicalExportName === entry.exportName
			? entry.exportName
			: `${canonicalExportName} as ${entry.exportName}`;
	return [
		header(version, detail),
		`export { ${renamed} } from "./${entry.aliasOf}";`,
		`export { ${canonicalExportName} as default } from "./${entry.aliasOf}";`,
		"",
	].join("\n");
}

/**
 * The barrel over every icon module.
 *
 * Each distinct export name appears exactly once, from the module that owns it.
 * A `subsumed` alias — one whose export name is already its own target's — is
 * skipped here and nowhere else: its module still exists, so the subpath import
 * still resolves, but the name is not exported twice.
 *
 * Importing anything from this file loads every icon module. That is a property
 * of roblox-ts, not a shortcoming of this file, and it is why the packages
 * document the per-icon subpath as the import to reach for. See `docs/LUCIDE.md`.
 */
export function renderBarrel(manifest: LucideManifest): string {
	const lines = [
		header(manifest.version, `${manifest.exportCount} icons`),
		"//",
		"// Importing from this barrel loads every icon module — roblox-ts has no",
		"// tree shaking. For a handful of icons, prefer the per-icon subpath:",
		"//",
		'//   import Search from "@rbxts/lucide-react/icons/search";',
		"",
	];
	for (const icon of manifest.icons) {
		if (icon.subsumed === true) {
			continue;
		}
		lines.push(`export { ${icon.exportName} } from "./icons/${icon.sourceName}";`);
	}
	lines.push("");
	return lines.join("\n");
}

/**
 * Renders the whole generated tree for one package.
 *
 * Called once per package with the same arguments, which is why the two trees
 * are identical.
 */
export function renderGeneratedTree(
	manifest: LucideManifest,
	compiled: readonly CompiledLucideIcon[],
): GeneratedFile[] {
	const compiledByName = new Map(compiled.map((icon) => [icon.sourceName, icon]));
	const exportNameBySourceName = new Map(
		manifest.icons.map((icon) => [icon.sourceName, icon.exportName]),
	);

	const files: GeneratedFile[] = [];
	for (const entry of manifest.icons) {
		const path = `src/generated/icons/${entry.sourceName}.tsx`;
		if (entry.aliasOf === undefined) {
			const icon = compiledByName.get(entry.sourceName);
			if (icon === undefined) {
				throw new Error(`Lucide emit: no compiled icon for "${entry.sourceName}".`);
			}
			files.push({
				path,
				contents: renderIconModule(icon, entry.exportName, manifest.version),
			});
		} else {
			const canonicalExportName = exportNameBySourceName.get(entry.aliasOf);
			if (canonicalExportName === undefined) {
				throw new Error(
					`Lucide emit: alias "${entry.sourceName}" targets "${entry.aliasOf}", which is not in the manifest.`,
				);
			}
			files.push({
				path,
				contents: renderAliasModule(entry, canonicalExportName, manifest.version),
			});
		}
	}

	files.push({ path: "src/generated/index.ts", contents: renderBarrel(manifest) });
	return files;
}
