#!/usr/bin/env node
/**
 * Prepares and runs the Lucide load/render benchmark.
 *
 * Not part of `pnpm test`. It exists to answer questions the packages make
 * claims about — what the eager root barrel actually costs, and whether a
 * hundred components or a hundred colour changes cost a hundred rasters — with
 * numbers rather than with reasoning.
 *
 * Run with:
 *
 *     pnpm generate:lucide && node tests/luau/bundle.mjs && node tests/luau/lucide-bench.mjs
 *
 * The generated fixture is every canonical icon's compiled IR, read back out of
 * the generated React modules rather than recompiled — so the benchmark
 * measures the bytes the package actually ships. It is large and derived, so it
 * is written beside the other generated Luau inputs and is not checked in.
 */

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../..");

const manifest = JSON.parse(
	readFileSync(join(repoRoot, "tools/lucide/manifest.json"), "utf8"),
);

/** Pulls the embedded base64 back out of a generated icon module. */
const EMBEDDED_IR = /"([A-Za-z0-9+/=]{40,})"/;

const rows = [];
for (const icon of manifest.icons) {
	if (icon.aliasOf !== undefined) {
		continue;
	}
	const source = readFileSync(
		join(repoRoot, `packages/lucide-react/src/generated/icons/${icon.sourceName}.tsx`),
		"utf8",
	);
	const match = EMBEDDED_IR.exec(source);
	if (match === null) {
		throw new Error(`no embedded IR found in generated module for ${icon.sourceName}`);
	}
	rows.push(`\t{ "${match[1]}", "${icon.hash}", "${icon.sourceName}" },`);
}

writeFileSync(
	join(here, "lucide-fixtures.luau"),
	`--!nocheck\n-- Generated by tests/luau/lucide-bench.mjs. Do not edit; do not commit.\nreturn {\n${rows.join("\n")}\n}\n`,
	"utf8",
);
process.stdout.write(`prepared ${rows.length} Lucide assets\n`);

execFileSync("luau", [join(here, "lucide-bench.luau")], { stdio: "inherit", cwd: here });
